# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '44 17 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
- name: Priority List

  # You may pin to the exact commit or the version.

  # uses: iterative/priority-list@646ca456f8a08495ae4c6259bd20ab274b9eaa03

  uses: iterative/priority-list@v1.0.2

  with:

    # Token with read access to all analysed repos

    github-token: 

    # 

    repos: 

    # weight for number of comments

    weight_activity: # default is 14

    # weight for reactions to original issue

    weight_reactions: # default is 7

    # weight for days of inactivity

    weight_staleness: # default is 1

    # weight for days open

    weight_age: # default is 0.142857

    # weight multiplier for PRs (compared to issues)

    multiplier_pr: # default is 7

    # weight multiplier for labels (negative to exclude)

    multiplier_labels: # default is example:-1 epic:0.142857 blocked:0.142857 invalid:0.142857

    # largest pN-label (lowest priority)

    p_label_graveyard: # default is 4

    # URL to post slack payload to (requires `people.json`)

    slack_webhook: #justin+berthelot+
    
